### PR TITLE
point-symbol=square label-text fix

### PR DESCRIPTION
**Pull request by cedricsam**
* Addresses https://github.com/mbloch/mapshaper/issues/240

### CODE REVIEW

**Comment by cedricsam** [comment]
Sorry for the multiple commits. I'm not doing this the right way... :\

**Comment by mbloch** [comment]
Hi Cedric, thanks for the pull request :)

I shouldn't have implemented square symbols by converting points to polygons where I did -- I must have been in a rush that day ;)

I think the code would be nicer if we passed an object containing layer-level style information as a second argument to `SVG.importGeoJSONFeatures()` and pass this style object through to the `importPoint()` function.  For example: `{point_symbol: "square"}`. Then you wouldn't have to recompute the label anchor from the polygon data, and text objects could be created in a single place.

Feel free to make this change if you like... or I can do it when I get a chance (probably not until next week sometime).

**Comment by cedricsam** [comment]
Hi Matt! Sounds good, and better. :)

The latest commit (https://github.com/cedricsam/mapshaper/commit/84fd6b1fc9d903b4a768368a2713f5c675d77d5a) implements the new workflow suggestion. I’m passing the entire layer options object to the `geojson-to-svg.js` to `importPoint` and `importMultiPoint`, if that’s fine.

I’m guessing that the plan is eventually to support other symbols, right? If we find a good way to represent a finite set of new symbols (star, concentric square/circle?), or even an arbitrary shape or glyph, it could be placed in this [switch statement](https://github.com/cedricsam/mapshaper/blob/84fd6b1fc9d903b4a768368a2713f5c675d77d5a/src/svg/geojson-to-svg.js#L182-L201). What do you think? And then maybe it might be good to have the whole `layerOpts` in there, so that funkier stuff can be done there.

**Comment by cedricsam** [comment]
Hmm, on second thought, I don’t think I’m actually doing this right, as I’m passing the global `-o` options, whereas I think you meant that you wanted to put `point_symbol` with the `-svg-style` options, correct? (Well, I re-read my code tomorrow or later this week, and resubmit a correct commit...)

**Comment by mbloch** [comment]
You gave yourself a thumbs-down emoji  :laughing: funny

I think your code is fine as an interim solution.

Ok, the `point-symbol=` option really should be part of the `-svg-style` command. The reason I added it to `-o` is because there is currently no way to pass style information between commands except to add it to the data properties of each feature, and it seemed odd to add {point_symbol: "square"} to every feature...  although that wouldn't be terrible, i guess.

An alternative might be to add an `"svg_style"` object to styled layers, containing style properties that apply to every feature in the layer. Need to think that through a bit more.

**Comment by mbloch** [comment]
To put this discussion in perspective:

Mapshaper's web UI can display basic polygon and polyline styles, but it's not a real WYSIWYG editor. I'm thinking about moving towards WYSIWYG by adding an SVG layer to the editor interface, so you could see SVG symbols like labels and icons as they would appear in your SVG output. You would also be able to edit labels directly.

Along with these changes, I'll want to move options for setting SVG output size and icon type from `-o` to `-svg-style`. But this is a medium-to-long term goal. In the meantime, I'm ok with leaving some styling options in the `-o` command, even if they don't seem to belong there.

**Comment by cedricsam** [comment]
Thanks, I think it would make a lot of sense, and be very useful for those of us who chiefly use SVG as output. Agreed on SVG options too. Do you have a roadmap / goals you'd want to accomplish? How much of an overhaul would it be to move the styling attributes out of simply adding the attribute to the feature, which you currently do right now?

**Comment by mbloch** [comment]
I'm not keen on moving per-feature style attributes out of the attribute table. If these styles are kept in a second table, then whenever a subsequent command caused features to be filtered, reordered or copied, the style table would have to be updated as well. It seems complicated and bug-prone.

It would be simpler to move only per-layer svg properties into a style object attached to the layer object. It would still take a bit of care to keep per-layer properties in sync with per-feature properties when layers are copied, split, etc.

Adding SVG rendering to the web UI seems like a much larger undertaking. Not sure about a timeline for working on this. It's not at the top of my personal wish list. Although it would be nice to be able to quickly position a bunch of labels by dragging with the mouse.

**Pull request merged**
